# playbook.yml
---
- hosts: 172.31.94.26
  become: yes
  tasks:
    - name: deploy application container
      docker_container:
        image: ajdurgam/helloworld-image
        name: helloworld-container
        state: started
        auto_remove: true
        ports:
          - "8081:8080"
