# playbook.yml
---
- hosts: localhost
  become: yes
  tasks:
    - name: deploy application container
      docker_container:
        image: ajdurgam/hello-image
        name: hello-container
        state: started
        auto_remove: true
        ports:
          - "8081:8080"
